# -*- coding: utf-8 -*-
"""covid19_cmp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gv-s9L7tiqv8tkfGInwdOROPSdrRRWuY
"""

#importing necessary libraries
import pandas as pd
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

#importing data from csv file
df=pd.read_csv('complete.csv')

#grouping on dates and suming cases from different states on specific dates
covid_cases=df.groupby('Date').sum()['Total Confirmed cases']

#converting it into a dataframe for ease of handling
df_covid_cases=pd.DataFrame(covid_cases)

#adding a column to mark day count starting from 2020-01-30 as day 0 with first noted covid19 case
df_covid_cases['Day']=1

#populating the Day column 
i=0
for value in df_covid_cases.index.values:
    df_covid_cases.loc[value]['Day']=i
    i=i+1

#defining the function to fit. other available non-linear functions are logrithmic, sigmoid
def exponential(x, Beta_1):
     y = np.exp(Beta_1*(x))
     return y

#seperating xdata and ydata data that should be before 14th April
df_beforeLD=df_covid_cases.loc['2020-01-30':'2020-04-14']
xdata=df_beforeLD['Day']
ydata=df_beforeLD['Total Confirmed cases']

#fit applied to obtain the value
#popt has the value of Beta_1
popt, pcov = curve_fit(exponential, xdata, ydata)

#generating and array of independent day value
X = np.arange(0,96,1)
#get y values for our X to plot the graph
plt.figure(figsize=(8,5))
y = exponential(X, *popt)
plt.plot(X,y,'--',label='Estimate, Had Lock Down Ended on 14th April')
plt.plot(df_covid_cases['Day'],df_covid_cases['Total Confirmed cases'],'r',label='Current Trend')
plt.legend(loc='best')
plt.ylabel('Total Number of Cases')
plt.xlabel('No. of Days from the first Covid19 case in India(2020-01-30 to 2020-05-04)')

